name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Run tests
      run: |
        docker-compose up --build --abort-on-container-exit

    - name: Create Allure results directory
      run: |
        mkdir -p test_results
        sudo chmod -R 777 test_results

    - name: Copy Allure report from Docker container
      run: |
        docker cp pytest_runner_works1:/tests_project/test_results ./test_results

    - name: Generate Allure Report
      run: allure generate ./test_results -o ./allure-report --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUBSECRET }}
        publish_dir: ./allure-report
