name: Запуск тестов и генерация отчета Allure

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Установка зависимостей
      run: |
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Запуск тестов
      run: |
        python -m pytest --alluredir=test_results/ tests/

    - name: Архивирование результатов тестов
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: test_results/

  generate-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Загрузка результатов тестов
      uses: actions/download-artifact@v2
      with:
        name: allure-results
        path: test_results

    - name: Установка Allure CLI
      run: sudo apt-get install allure -y

    - name: Генерация отчета Allure
      run: allure generate test_results/ -o allure-report/ --clean

    - name: Публикация отчета Allure на GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: allure-report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBSECRET }}

